name: zabbix_inst

on:
  push:
    branches:
      - main

jobs:
  install_zabbix-agent:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Download Deb
        run: wget https://repo.zabbix.com/zabbix/4.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_4.0-2+bionic_all.deb
        
      - name: Append the repository
        run: sudo dpkg -i zabbix-release_4.0-2+bionic_all.deb
        
      - name: Install zabbix-agent
        run: sudo apt install zabbix-agent
        
      - name: Enable zabbix-agent
        run: systemctl status zabbix-agent
        #|
        #  systemctl restart zabbix-agent
        #  systemctl enable zabbix-agent
        
      - name: Check zabbix-agent version
        run: /usr/sbin/zabbix_agentd --V
