name: zabbix_inst

on:
  push:
    branches:
      - main

jobs:
  install_zabbix-agent:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Epel Release
        run: yum -y install epel-release

      - name: Download RPM
        run: dnf install https://repo.zabbix.com/zabbix/4.4/rhel/8/x86_64/zabbix-release-4.4-1.el8.noarch.rpm
        
      - name: Install zabbix-agent
        run: dnf install zabbix-agent
        
      - name: Check version
        run: zabbix-agent --V
